name: msa-acom-paper
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.10
  - jupyterlab
  - numpy
  - matplotlib
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - pymatgen
      - py4DSTEM
