name: msa-acom-paper
channels:
  - default
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - matplotlib
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - h5py
      - pymatgen
      - py4DSTEM==0.12.24
